version: '2'
services:
  myztl4-app:
    image: myztl4
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://myztl4-postgresql:5432/myZTL4
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8081:8081
  myztl4-postgresql:
    extends:
      file: postgresql.yml
      service: myztl4-postgresql
